name: 'Email Notification Workflow'

on:  
  workflow_dispatch:  
  schedule:    
    - cron: '0 8 * * Mon'

jobs:  
  email:    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4

      - name: "Convert Notebook to Clean HTML"
        run: |
          pip install jupyter
          pip install -r requirements.txt
          jupyter nbconvert --to html --template basic --execute --no-input --TemplateExporter.exclude_markdown=True analysis.ipynb --output analysis_clean.html
      - name: "Send Mail"
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          username: ${{ secrets.GOOGLE_USERNAME }}
          password: ${{ secrets.GOOGLE_APP_SECRET }}
          subject: "Github Actions Test: Analysis Report"
          to: peter.hedman@gmail.com
          from: peter.hedman@gmail.com
          html_body: file://analysis_clean.html
